---

- name: create switch port
  command: >-
    ovn-nbctl --db={{ ovn_nb_db }}
    --may-exist
    lsp-add
    {{ item.connect_switch }}
    {{ item.ovs_id }}
  loop: "{{ target.iface_list }}"

- name: connect switch port
  command: >-
    ovn-nbctl --db={{ ovn_nb_db }}
    lsp-set-addresses
    {{ item.ovs_id }}
    {{ item.mac }}
  loop: "{{ target.iface_list }}"
