---
- name: destroy vm
  hosts: kvm
  become: yes
  tasks:

    - name: destory net
      include_role:
        name: net
      vars:
        net_action: destroy
        target: "{{ item }}"
      loop: "{{ vm_list }}"
      when:
        - item.meta.state == "deploy"
        - item.meta.host == inventory_hostname
        - item.meta.sdn is defined
      tags: destroy_develop

    - name: destory vm
      include_role:
        name: vm
      vars:
        vm_action: destroy
        target: "{{ item }}"
      loop: "{{ vm_list }}"
      when:
        - item.meta.state == "deploy"
        - item.meta.host == inventory_hostname
      tags: destroy_develop
