---
- name: destroy vm
  hosts: kvm
  become: yes
  tasks:

    - name: destory develop
      import_role:
        name: vm
      vars:
        vm_action: destroy
        target: develop
      tags: destroy_develop
