---
- name: destroy vm
  hosts: kvm_worker
  become: yes
  tasks:

    - name: destory vm
      include_role:
        name: vm
      vars:
        vm_action: destroy
        target: "{{ item }}"
      loop: "{{ vm_list }}"
      when:
        - item.meta.label == "deploy"
        - item.meta.host == inventory_hostname
      tags: destroy_develop
