---
- name: destroy vm
  hosts: kvm
  become: yes
  tasks:

    - name: destory docker-build
      import_role:
        name: vm
      vars:
        vm_action: destroy
        target: docker-build
      tags: destroy_docker_build
