---
- name: setup vm
  hosts: kvm
  become: yes
  tasks:

    - name: start develop vm
      include_role:
        name: vm
      vars:
        vm_action: start
        src_image: rocky9
        target: "{{ item }}"
      loop: "{{ vm_list }}"
      when: item.meta.label == "develop"
      tags: start_develop

    - name: Waits for develop
      wait_for:
        host: "{{ item.ip }}"
        port: 22
        delay: 10
      loop: "{{ vm_list }}"
      when: item.meta.label == "develop"
      tags: health_check_develop
