---

- name: install vm dependencies
  hosts: kvm
  become: yes
  tasks:

    - name: repo update
      ansible.builtin.package:
        name: '*'
        state: latest
      when: kvm_install is defined

    - name: install packages
      ansible.builtin.package:
        name:
          - qemu-kvm
          - libvirt-daemon-system
          - libvirt-clients
          - virtinst
          - bridge-utils
          - libosinfo-bin
          - guestfs-tools
        state: latest
      when: kvm_install is defined

- name: setup vm
  hosts: kvm
  become: yes
  tasks:

    - name: deploy vm
      include_role:
        name: vm
      vars:
        vm_action: start
        target: "{{ item }}"
      loop: "{{ vm_list }}"
      when:
        - item.meta.state == "start"
        - item.meta.host == inventory_hostname
      tags: start_deploy

    - name: deploy net
      include_role:
        name: net
      vars:
        net_action: start
        target: "{{ item }}"
      loop: "{{ vm_list }}"
      when:
        - item.meta.state == "start"
        - item.meta.host == inventory_hostname
        - item.meta.sdn is defined
      tags: start_deploy

    - name: Waits for deploy
      wait_for:
        host: "{{ (item.iface_list | first ).ip }}"
        port: 22
        delay: 10
      loop: "{{ vm_list }}"
      when:
        - item.meta.state == "start"
        - item.meta.host == inventory_hostname
      tags: health_check_develop
