---
- name: setup vm
  hosts: kvm
  become: yes
  tasks:

    - name: setup dns resolver
      import_role:
        name: pdns_recursor
      tags:
        - setup
        - setup_pdns_recursor

    - name: setup dhcpd
      import_role:
        name: dhcpd
      tags:
        - setup
        - setup_dhcpd

    - name: start develop
      import_role:
        name: vm
      vars:
        vm_action: start
        src_image: rocky9
        target: develop
      tags: start_develop

    - name: Waits for develop
      ansible.builtin.wait_for:
        host: "{{ (kvm_vm_list | selectattr('name', 'eq', 'develop') | list)[0].ip }}"
        port: 22
        delay: 10
      tags: health_check_develop
