---
- name: setup vm
  hosts: kvm
  become: yes
  tasks:

    - name: setup dhcpd
      import_role:
        name: dhcpd
      tags: setup_dhcpd

    - name: start docker-build
      import_role:
        name: vm
      vars:
        vm_action: start
        src_image: rocky9
        target: docker-build
      tags: start_docker_build
