---

- name: set search_string
  set_fact:
    search_string: "{{ ' ' ~ target.name ~ ' ' }}"

- name: check vm_list
  command: >-
    virsh list
  register: virsh_list
  changed_when: false

- name: destroy vm
  command: >-
    virsh destroy {{ target.name }}
  changed_when: true
  when: search_string in virsh_list.stdout

- name: check vm_list_all
  command: >-
    virsh list --all
  register: virsh_list_all
  changed_when: false

- name: undefine vm
  command: >-
    virsh undefine {{ target.name }}
  changed_when: true
  when: search_string in virsh_list_all.stdout

- name: destory qcow2
  file:
    path: "{{ qcow_dir }}/{{ target.name }}.qcow2"
    state: absent

- name: destory xml
  file:
    path: "{{ xml_dir }}/{{ target.name }}.xml"
    state: absent
