---

- name: check virsh list
  command: >-
    virsh list
  register: virsh_list
  changed_when: false

- name: create qcow2
  command: >-
    cp {{ qcow_dir }}/{{ src_image }}.qcow2 {{ qcow_dir }}/{{ target.name }}.qcow2
  when:
    - target.name not in virsh_list.stdout
    - src_image is defined

- name: set xml
  template:
    src: "vm.xml.j2"
    dest: "{{ xml_dir }}/{{ target.name }}.xml"
    owner: root
    group: root
    mode: 0644
  when:
    - target.name not in virsh_list.stdout

- name: define vm
  command: >-
    virsh define {{ xml_dir }}/{{ target.name }}.xml
  changed_when: true
  when:
    - target.name not in virsh_list.stdout

- name: start vm
  command: >-
    virsh start {{ target.name }}
  changed_when: true
  when:
    - target.name not in virsh_list.stdout
