---

- name: set search_string
  set_fact:
    search_string: "{{ ' ' ~ target.name ~ ' ' }}"

- name: check virsh list
  command: >-
    virsh list
  register: virsh_list
  changed_when: false

- name: create qcow2
  command: >-
    cp {{ qcow_dir }}/{{ target.base_os }}.qcow2 {{ qcow_dir }}/{{ target.name }}.qcow2
  when:
    - search_string not in virsh_list.stdout

- name: set xml
  template:
    src: "{{ target.base_os }}.xml.j2"
    dest: "{{ xml_dir }}/{{ target.name }}.xml"
    owner: root
    group: root
    mode: 0644
  when:
    - search_string not in virsh_list.stdout

- name: define vm
  command: >-
    virsh define {{ xml_dir }}/{{ target.name }}.xml
  changed_when: true
  when:
    - search_string not in virsh_list.stdout

- name: start vm
  command: >-
    virsh start {{ target.name }}
  changed_when: true
  when:
    - search_string not in virsh_list.stdout
