---

- name: create dir
  file:
    path: /etc/dhcp
    state: directory
    owner: root
    group: root
    mode: 0750

- name: setting /etc/dhcp/dhcpd.conf
  template:
    src: dhcpd.conf.j2
    dest: /etc/dhcp/dhcpd.conf
    owner: root
    group: root
    mode: 0644
