---

- name: install epel-release
  dnf:
    name: epel-release
    state: latest

- name: setup repo
  command: >-
    curl -o /etc/yum.repos.d/powerdns-rec-master.repo https://repo.powerdns.com/repo-files/el-rec-master.repo
  changed_when: true

- name: install pdns-recursor
  dnf:
    name: pdns-recursor
    state: latest
