---

- name: setting pdns recursor
  import_tasks: setting.yml
  tags: setting_pdns_recursor

- name: force restart pdns-recursor
  debug:
    msg: force restart pdns-recursor
  when: force_restart_pdns_recursor | default(False) | bool
  changed_when: true
  notify: restart_pdns_recursor
  tags: restart_pdns_recursor
